# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b43400ee-e3b6-401f-a975-4c360a7d5ea3";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = 1;
  virtualisation.virtualbox.guest.enable = true;
}
